services:
  fantasy_store:
    build: .
    container_name: fantasy_store
    volumes:
      - .:/app
    ports:
      # - "59900:8000"
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - fantasy_mongodb
    # For localhost
    # command: sleep infinity
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    working_dir: /app
    environment:
      - PYTHONPATH=/app

  fantasy_mongodb:
      image: mongo:latest
      container_name: fantasy_mongodb
      volumes:
        - ./docker_volumes/mongodb:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=fantasy
        - MONGO_INITDB_ROOT_PASSWORD=fantasy
        - MONGO_INITDB_DATABASE=fantasy_back
      ports:
        - "27017:27017"
